### ISSUE TITLE
Option to remove panel borders

### ISSUE THREAD

**Issue by ProLoser** [cdonohue/clean-ui#1]
I have generally used Atom Material theme which does not place borders on panels and creates a really nice look. I think they have an option to add box shadows. Would it be possible to have an option to remove borders on panels and/or add box shadows instead?

**Comment by cdonohue** [comment]
@ProLoser, I actually have an update going out soon (within a day), which removes `pane` borders. I believe this cleans the interface up a bit more.

<img width="923" alt="screenshot 2016-10-19 02 29 36" src="https://cloud.githubusercontent.com/assets/1928846/19509372/0a539b6c-95a4-11e6-9f18-dfdb7208edfd.png">

Would something like this work?

**Comment by cdonohue** [comment]
This update is live, let me know if it works for you, @ProLoser
