### ISSUE TITLE
Theme not installable in Atom 1.12.1

### ISSUE THREAD

**Issue by itsgg** [cdonohue/clean-ui#1]
→ apm install clean-ui
Installing clean-ui to /Users/gg/.atom/packages ✗
Unable to download https://www.atom.io/api/packages/clean-ui/versions/1.8.2/tarball: 400 Bad Request Repository inaccessible

**Comment by NeoMurderer** [comment]
Same problem

**Comment by cdonohue** [comment]
See #1
