### ISSUE TITLE
Can't resize tree view panel (horizontally)

### ISSUE THREAD

**Issue by ctrlplusb** [cdonohue/clean-ui#2]
![clean-ui-treeview-issue](https://cloud.githubusercontent.com/assets/12164768/19579304/c9925634-9717-11e6-934a-beacd04fd6f6.gif)

**Comment by cdonohue** [comment]
I'll look into making this an option, @ctrlplus.

The width is locked here:
> https://github.com/cdonohue/clean-ui/blob/master/styles/tree-view.less#L121

That was a very strong opinion brought over from the custom stylesheet that I use 😄 . Maybe an option to have be fixed or movable?

**Comment by cdonohue** [comment]
Actually, now that I think about it, it would probably be better left to the user to add it to their custom stylesheet of they want the `fixed` behavior. Then, it's movable from the start and there is no need really for a `fixed` config option. 

``` less
.tree-view-resizer {
  width: 256px !important;
}
```

**Comment by cdonohue** [comment]
This is solved with #3
